### ISSUE TITLE
Rules are applied to all the code

### ISSUE THREAD

**Issue by reeflog** [DavidArno/Arnolyzer#5]
I had in mind to write something similar than you but with the current implementation rules are applied to all the codes. It's preventing to write usual object programing for instance with "AA1100 - Interface Properties Should Be Read-Only".
What do you think about applying rules only when attributes are used ? For instance, applying pure function rules only when PureAttrbute is set to a method.

**Comment by DavidArno** [comment]
@reeflog,

Apologies for being so slow in replying to this.

That would be possible, but to be honest, it's not something I'd want to do. The whole idea behind Arnolyzer is that it takes the "pit of success" route: having eg immutability as the default and requiring extra work to enable mutability. What you are suggesting is unfortunately the opposite of this central idea.

Of course, you are free to fork the code and create your own version that works this way as the project is covered by the MIT licence and thus you can take it and do what you want with it :smile:
